set backspace=2         " backspace in insert mode works like normal editor
set shiftwidth=2        " indent by 2 spaces when auto-indenting
set softtabstop=2       " indent by 2 spaces when hitting tab
syntax on               " syntax highlighting
filetype indent on      " activates indenting for files
set autoindent          " auto indenting
set number              " line numbers
set ruler               " line/coloumn number
colorscheme desert      " colorscheme desert
set nobackup            " get rid of anoying ~file

"Set w!! to write with sudo
cmap w!! w !sudo tee > /dev/null %   

set mouse=a
