actions:
  executable: chmod +x $HOME/.scripts/*.sh
config:
  backup: false
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
  link_on_import: nolink
  minversion: 0.29.4
dotfiles:
  d_compton:
    dst: ~/.config/compton
    src: config/compton
  d_fonts:
    dst: ~/.local/share/fonts
    src: local/share/fonts
  d_i3:
    dst: ~/.config/i3/config
    src: config/i3/config
  d_polybar:
    dst: ~/.config/polybar
    src: config/polybar
  d_pulseaudio-ctl:
    dst: ~/.config/pulseaudio-ctl
    src: config/pulseaudio-ctl
  d_scripts:
    actions:
    - executable
    dst: ~/.scripts
    src: scripts
  d_setmonitor:
    dst: ~/.setmonitor
    src: setmonitor
  d_zsh-autosuggestions:
    dst: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    src: oh-my-zsh/custom/plugins/zsh-autosuggestions
  d_zsh-syntax-highlighting:
    dst: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    src: oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  f_config.cson:
    dst: ~/.atom/config.cson
    src: atom/config.cson
  f_github.cson:
    dst: ~/.atom/github.cson
    src: atom/github.cson
  f_package.list:
    dst: ~/.atom/package.list
    src: atom/package.list
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  home:
    dotfiles:
    - f_vimrc
    - f_zshrc
    - f_config.cson
    - f_github.cson
    - f_package.list
    - d_fonts
    - d_zsh-autosuggestions
    - d_i3
    - d_setmonitor
    - d_scripts
    - d_pulseaudio-ctl
    - d_polybar
    - f_xresources
    - d_compton
    - d_zsh-syntax-highlighting
  apollo:
    dotfiles:
    - f_vimrc
    - f_zshrc
    - d_fonts
    - d_zsh-autosuggestions
    - d_zsh-syntax-highlighting
    - d_scripts
  work_mac:
    dotfiles:
    - f_vimrc
    - f_zshrc
    - f_config.cson
    - f_github.cson
    - f_package.list
    - d_fonts
    - d_zsh-autosuggestions
    - d_scripts
    - d_zsh-syntax-highlighting
  work_ubuntu:
    dotfiles:
    - f_vimrc
    - f_zshrc
    - d_fonts
    - d_zsh-autosuggestions
    - d_zsh-syntax-highlighting
